name: CI

on:
  push:
    branches:
      - latest
      - refactor
      - dev
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "build" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"

      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Install deps
      - run: npm install --quiet

      # Run CI
      - run: npm ci
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: latest

      # Lint, test and build
      - run: npx nx run-many -t lint test build --all --skip-nx-cache

      # Cargo configuration
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check --target-dir=libs/luna-api

